$(document).ready(function(){
   $("img#cons").click(function(){
$("#first-icon").toggle();
   });
   $("img#con").click(function(){
$("#second-icon").toggle();
   });
   $("img#coni").click(function(){
$("#third-icon").toggle();
   });
});
