$(document).ready(function(){
   $(".cons").click(function(){
$(".clcs").toggle();
    $(".first-icon").toggle();
   });
   $(".cons").click(function(){
    $(".clcs").toggle();
        $(".first-icon").toggle();
       });
   /****developmennt*/
   $("img.con").click(function(){
      $('.cls1').toggle();
      $(".second-icon").toggle();
   });
   $(".second-icon").click(function(){
    $(".cls1").toggle();
    $(".second-icon").toggle();
 });
  $("img.coni").click(function(){
      $(".cls2").toggle();
 $(".third-icon").toggle();

   });
});
